### ISSUE TITLE
 table "mantis_bug_table" in the database does not have a column called "category"

### ISSUE THREAD

**Issue by zhanglei0110** [nonplus/mantis2gitlab#8]
Hello, I have installed version mantisbt2.20.0 and found that the table "mantis_bug_table" in the database does not have a column called "category". The column it really represents is called "category_id". It may be because my version is too new
thank you

**Comment by nonplus** [comment]
The script is 4 years old, so I wouldn't be surprised if it doesn't work with current versions of Mantis and GitLab.

Maybe one of the forks works with your versions?  Otherwise, feel free to fork it and adapt it to your needs.
